import Navigation from '@/components/Navigation'
import type { Metadata } from 'next'
import { DM_Sans, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] })
const dmsans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dmsans',
})

export const metadata: Metadata = {
  title: 'Marketo',
  description: 'Generated by SazzadTanim',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${dmsans.variable} font-sans w-full bg-white bg-test bg-top bg-no-repeat object-fill`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  )
}
